import type { APIRoute } from 'astro';

export const prerender = false;

const demos = [
  {
    id: '1',
    name: 'Campus Maya',
    description: 'Eğitim kurumları için entegre yönetim sistemi. Öğrenci, ders, sınıf ve not yönetimi.',
    category: 'Eğitim',
    image: '/placeholder-demo-1.svg',
    features: [
      'Öğrenci yönetimi',
      'Sınıf yönetimi',
      'Not sistemi',
      'Ders programı',
      'Veli paneli',
      'Rapor oluşturma',
    ],
    createdAt: '2025-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'Hastane Yönetim Sistemi',
    description: 'Sağlık kurumları için hasta kayıt, randevu ve tıbbi kayıt yönetimi.',
    category: 'Sağlık',
    image: '/placeholder-demo-2.svg',
    features: [
      'Hasta kayıt',
      'Randevu yönetimi',
      'Tıbbi kayıtlar',
      'İlaç envanteri',
      'Doktor takvimi',
      'Klinik raporları',
    ],
    createdAt: '2025-01-15T11:00:00Z',
  },
  {
    id: '3',
    name: 'Perakende Yönetim Sistemi',
    description: 'Mağaza ve satış noktaları için envanter ve satış yönetimi.',
    category: 'Perakende',
    image: '/placeholder-demo-3.svg',
    features: [
      'Ürün envanteri',
      'Satış yönetimi',
      'Müşteri ilişkileri',
      'Kasa entegrasyonu',
      'Depo yönetimi',
      'Satış raporları',
    ],
    createdAt: '2025-01-15T12:00:00Z',
  },
  {
    id: '4',
    name: 'Otel Rezervasyon Sistemi',
    description: 'Oteller için oda yönetimi, rezervasyon ve misafir hizmetleri.',
    category: 'Konaklama',
    image: '/placeholder-demo-4.svg',
    features: [
      'Oda yönetimi',
      'Rezervasyon sistemi',
      'Fatura yönetimi',
      'Personel planlama',
      'Misafir profilleri',
      'İstatistikler',
    ],
    createdAt: '2025-01-15T13:00:00Z',
  },
  {
    id: '5',
    name: 'Lojistik Takip Sistemi',
    description: 'Kargo ve lojistik şirketleri için gönderi takip ve yönetimi.',
    category: 'Lojistik',
    image: '/placeholder-demo-5.svg',
    features: [
      'Gönderi takip',
      'Rota optimizasyonu',
      'Şoför yönetimi',
      'Araç envanteri',
      'Teslimat onayı',
      'Analytics',
    ],
    createdAt: '2025-01-15T14:00:00Z',
  },
  {
    id: '6',
    name: 'Avukat Ofisi Yönetim',
    description: 'Hukuk firmaları için dosya, müşteri ve proje yönetimi.',
    category: 'Hukuk',
    image: '/placeholder-demo-6.svg',
    features: [
      'Dosya yönetimi',
      'Müşteri takip',
      'Saat kaydı',
      'Fatura otomasyonu',
      'Tarih hatırlatması',
      'Rapor oluşturma',
    ],
    createdAt: '2025-01-15T15:00:00Z',
  },
  {
    id: '7',
    name: 'İmalat Planlama Sistemi',
    description: 'Üretim şirketleri için üretim planlama ve kalite kontrolü.',
    category: 'İmalat',
    image: '/placeholder-demo-7.svg',
    features: [
      'Üretim planlama',
      'Kalite kontrolü',
      'Hammadde yönetimi',
      'Makine bakımı',
      'İşçi performansı',
      'Üretim raporları',
    ],
    createdAt: '2025-01-16T10:00:00Z',
  },
  {
    id: '8',
    name: 'Gayrimenkul Yönetimi',
    description: 'Emlak acenteleri ve yatırımcılar için mülk yönetimi ve satış takip.',
    category: 'Gayrimenkul',
    image: '/placeholder-demo-8.svg',
    features: [
      'Mülk veritabanı',
      'İlan yönetimi',
      'Müşteri yönetimi',
      'Kiralama takip',
      'Gelir raporları',
      'Belge arşivi',
    ],
    createdAt: '2025-01-16T11:00:00Z',
  },
  {
    id: '9',
    name: 'Resepsiyon Yönetim',
    description: 'Klinlik, spor salonu ve danışmanlık şirketleri için randevu ve üyelik yönetimi.',
    category: 'Hizmetler',
    image: '/placeholder-demo-9.svg',
    features: [
      'Randevu yönetimi',
      'Üyelik takip',
      'Ödeme işleme',
      'SMS bildirimleri',
      'Personel planlama',
      'Müşteri geçmişi',
    ],
    createdAt: '2025-01-16T12:00:00Z',
  },
  {
    id: '10',
    name: 'Muhasebe Yazılımı',
    description: 'Tüm işletmeler için muhasebe, vergi ve finansal raporlama.',
    category: 'Muhasebe',
    image: '/placeholder-demo-10.svg',
    features: [
      'Günlük defter',
      'Faturalama',
      'Vergi raporları',
      'Cari yönetimi',
      'Banka mutabakat',
      'Mali analizler',
    ],
    createdAt: '2025-01-16T13:00:00Z',
  },
  {
    id: '11',
    name: 'Envanter Yönetim Sistemi',
    description: 'Depo ve stok yönetimi otomasyonu.',
    category: 'Lojistik',
    image: '/placeholder-demo-11.svg',
    features: [
      'Stok takip',
      'Depo yönetimi',
      'Ürün kategorileri',
      'Barkod taraması',
      'Reorder sistemi',
      'Depo raporları',
    ],
    createdAt: '2025-01-16T14:00:00Z',
  },
  {
    id: '12',
    name: 'İnsan Kaynakları Sistemi',
    description: 'Personel yönetimi, bordro ve performans değerlendirmesi.',
    category: 'İnsan Kaynakları',
    image: '/placeholder-demo-12.svg',
    features: [
      'Personel dosyaları',
      'Bordro yönetimi',
      'İzin takip',
      'Performans değerlendirmesi',
      'Organizasyon şeması',
      'Eğitim planlama',
    ],
    createdAt: '2025-01-16T15:00:00Z',
  },
  {
    id: '13',
    name: 'Satış ve CRM',
    description: 'Müşteri ilişkileri ve satış fırsatları yönetimi.',
    category: 'Satış',
    image: '/placeholder-demo-13.svg',
    features: [
      'Müşteri tabanı',
      'Satış fırsatları',
      'E-mail kampanyaları',
      'Satış tüneği',
      'Satış raporları',
      'Takip görevleri',
    ],
    createdAt: '2025-01-17T10:00:00Z',
  },
  {
    id: '14',
    name: 'Proje Yönetim Aracı',
    description: 'Yazılım ve danışmanlık projelerinin yönetimi.',
    category: 'Proje Yönetimi',
    image: '/placeholder-demo-14.svg',
    features: [
      'Proje planlama',
      'Görev atama',
      'Zaman takip',
      'Bütçe yönetimi',
      'Takım işbirliği',
      'İlerleme raporları',
    ],
    createdAt: '2025-01-17T11:00:00Z',
  },
  {
    id: '15',
    name: 'Teknik Destek Sistemi',
    description: 'Müşteri destek ve hata izleme sistemi.',
    category: 'Destek',
    image: '/placeholder-demo-15.svg',
    features: [
      'Destek talepleri',
      'Hata izleme',
      'Bilgi tabanı',
      'Canlı sohbet',
      'Öncelik yönetimi',
      'İstatistikler',
    ],
    createdAt: '2025-01-17T12:00:00Z',
  },
  {
    id: '16',
    name: 'Yönetim Kontrol Paneli',
    description: 'İşletme metriklerinin merkezi yönetim ve monitoring.',
    category: 'Analitics',
    image: '/placeholder-demo-16.svg',
    features: [
      'KPI takip',
      'Gerçek zamanlı veriler',
      'Özel raporlar',
      'Veri görselleştirme',
      'Uyarı sistemi',
      'Tahmin analizi',
    ],
    createdAt: '2025-01-17T13:00:00Z',
  },
  {
    id: '17',
    name: 'Etkinlik Yönetim Sistemi',
    description: 'Konferans, seminer ve etkinlik yönetimi.',
    category: 'Etkinlikler',
    image: '/placeholder-demo-17.svg',
    features: [
      'Etkinlik planlama',
      'Bilet satışı',
      'Katılımcı kaydı',
      'Alan planlaması',
      'İletişim otomasyonu',
      'Raporlama',
    ],
    createdAt: '2025-01-17T14:00:00Z',
  },
  {
    id: '18',
    name: 'Eğitim Platformu',
    description: 'Online ve yüz yüze eğitim yönetimi.',
    category: 'Eğitim',
    image: '/placeholder-demo-18.svg',
    features: [
      'Kurs yönetimi',
      'Sınıf takip',
      'Ödev yönetimi',
      'Öğrenme ilerlemesi',
      'Sertifika sistemi',
      'Öğrenci raporları',
    ],
    createdAt: '2025-01-17T15:00:00Z',
  },
  {
    id: '19',
    name: 'Restoran Yönetim Sistemi',
    description: 'Restoran ve café işletmeleri için menu, sipariş ve yönetim.',
    category: 'Gıda & İçecek',
    image: '/placeholder-demo-19.svg',
    features: [
      'Menu yönetimi',
      'Sipariş sistemi',
      'Masa yönetimi',
      'Mutfak monitörü',
      'Kasa sistemi',
      'İşletme raporları',
    ],
    createdAt: '2025-01-18T10:00:00Z',
  },
  {
    id: '20',
    name: 'Ziraat Yönetimi',
    description: 'Tarım işletmeleri için bitki, hayvan ve ürün yönetimi.',
    category: 'Tarım',
    image: '/placeholder-demo-20.svg',
    features: [
      'Tarlalar haritası',
      'Ürün takip',
      'Hayvan kayıtları',
      'Verim analizi',
      'Hava durumu takip',
      'Mahsul planlama',
    ],
    createdAt: '2025-01-18T11:00:00Z',
  },
  {
    id: '21',
    name: 'Dişçi Klinik Yönetimi',
    description: 'Diş kliniği için hasta takip ve tedavi planlama.',
    category: 'Sağlık',
    image: '/placeholder-demo-21.svg',
    features: [
      'Hasta profilleri',
      'Tedavi planlama',
      'Randevu sistemi',
      'Diş haritası',
      'İlerleme fotoları',
      'Ödeme takip',
    ],
    createdAt: '2025-01-18T12:00:00Z',
  },
];

export const GET: APIRoute = async ({ params }) => {
  const { id } = params;

  // GET /api/demos/:id
  if (id) {
    const demo = demos.find((d) => d.id === id);
    if (!demo) {
      return new Response(JSON.stringify({ error: 'Demo not found' }), {
        status: 404,
        headers: { 'Content-Type': 'application/json' },
      });
    }
    return new Response(JSON.stringify(demo), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  // GET /api/demos
  return new Response(JSON.stringify(demos), {
    status: 200,
    headers: { 'Content-Type': 'application/json' },
  });
};
